"""Generate the runtime language capability matrix."""

from __future__ import annotations

from pathlib import Path

from spokenform import language_support, resolve_abbr2words_language, supported_languages

ROOT = Path(__file__).parents[1]
OUTPUT = ROOT / "docs" / "language-coverage.md"


def render() -> str:
    lines = [
        "# Generated language coverage",
        "",
        "<!-- Generated by scripts/generate_language_coverage.py. Do not edit manually. -->",
        "",
        "Spokenform accepts 49 base families and 17 explicit dependency locale overlays.",
        "Specialist capabilities remain independent from global language acceptance.",
        "",
        "| Spokenform key | Dependency key | Exact locale | Abbreviations | Number backend | Decimal policy | Structured | Sequence policy | KokoroG2P | Tier |",
        "| --- | --- | ---: | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for language in supported_languages(include_locales=True):
        support = language_support(language)
        dependency = resolve_abbr2words_language(language)
        lines.append(
            "| `{language}` | `{dependency}` | {exact} | yes | {backend} | {decimal} | {structured} | {sequence} | {kokoro} | {tier} |".format(
                language=language,
                dependency=dependency,
                exact="yes" if support.exact_locale else "no",
                backend=support.number_backend or "none",
                decimal="yes" if support.decimal_policy else "no",
                structured="yes" if support.structured else "no",
                sequence="yes" if support.sequence_policy else "no",
                kokoro="yes" if support.kokorog2p_profile else "no",
                tier=support.tier.value,
            )
        )
    lines.extend(
        [
            "",
            "`kk` is Spokenform's public Kazakh key and routes to dependency key `kz`.",
            "A `none` number backend means ordinary numeric source is preserved by normal `prepare()`.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    OUTPUT.write_text(render(), encoding="utf-8")


if __name__ == "__main__":
    main()
